module.exports=
{
	postMethod:'POST',
	homePage:'/',
	authenticate:'/auth',
	authRouteURL:'./routes/authRoutes',
	addTemplatesDataIntoDBThroughJSONFile:'/createTemplates',
	dynamicTemplatesDataJSONFileLocation:'./JSON/dynamicTemplates.json',
	forgotPasswordRouteURL:'./routes/forgotPassword',
	updateTemplateRouteURL:'./routes/updateTemplate',
	defaultViewFolder:'/public',
	indexPageRouteURL:'pages/index',
	homePageRouteURL:'pages/home',
	successPageRouteURL:'pages/successpage',
	createTemplateRouteURL:'/templateCreation',
	createDynamicaTemplateRouteURL:'pages/dynamicTemplatePage',
	displayAllTemplatesRouteURL:'/show_all_templates',
	getAllTemplatesRouteURL:'pages/getAllTemplateDetails',
	getForgotPasswordURL:'/forgotpassword',
	deleteTemplates:'/deleteTemplate',
	sucessPageURL:'/success',
	statusURL:'/status',
	statusPageURL:'pages/status',
	statusMsg:'Your request is InProcess',
	userExistStatus:'user details are already existed please login',
	passwordIncorrect:'Entered password incorrect',
	userNotRegisterMsg:'Your are not registered, please register first',
	faildAuthenticationMsg:'Failed to authenticate token.',
	enterCorrectEmailId:'Please enter correct eamil',
	unauthorizedMessage:'Your are not authorized person to access this service',
	passwordTitle:'Password',
	passwordSubject:'Password from thechitrakars.com',
	passwordSentense:'Your password is',
	checkYourMailAndLogin:'Please check your mail and login',
	templateURLId:'/:id',
	false:'false',
	true:'true',
	ejsFileLocation:'/views/'+'templates/',
	templatesLocation:'templates/',
	logout:'/logout',
	prepareObjectRouteURL:'/prepareObject',
	filePathOfPrepare:'./routes/prepare',
	createDynamicTemplate:'/createTemplate',
	createDynamicTemplaterouteURL:'./routes/templateCreation',
	updateTemplate:'/updatetemplate',
	signInRouteURL:'/signIn',
	profileRouteURL:'/profile',
	createObject:'/createObj',
	jWTSecretKey:'superSecret',
	authProfileRouteURL:'/auth/profile',
  	featureVideoConstant : 'featureVideo',
  	xCursorposition : 'xCursorposition',
  	yCursorposition :'yCursorposition',
	base64Constant :'base64',
	pngImageExtension:".png",
  	videoMP4 : '.mp4',
  	dateFormatWithSec : 'DDMMYYYYHHmmss',
  	routeImageslash : "./public/projectImages/",
	output :  'output',
	module : 'module',
	reqId : 'req_id',
	videoRender : 'video_render',
	generatedVedioPath : 'Video/',
	routeImageUserPath : './public/projectImages/userFile_',
	octStream : '.octet-stream',
	emailSubjectNotif : 'Notification',
	emailTittleFromCh : 'Notification from thechitrakars.com',
	textVideoSoon : 'You will get your video soon',
	emailBodyStatus :'Status',
	statusReady : 'ready',
	formJson : 'formJson',
  	serverCloseMessage:  'Unfortunately server was closed please login once again',
}